# Generated by Django 3.2 on 2024-08-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0002_auto_20240821_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classification_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/'),
        ),
    ]
