# Generated by Django 3.2 on 2024-08-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0002_delete_userstylekeyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CafeKeyword',
        ),
        migrations.AddField(
            model_name='user',
            name='style_keywords',
            field=models.ManyToManyField(blank=True, related_name='users', to='coplate.StyleKeyword'),
        ),
    ]
