# Generated by Django 3.2 on 2024-08-20 15:14

import coplate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0003_auto_20240820_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='image1',
            field=models.ImageField(blank=True, upload_to=coplate.models.cafe_image_upload_to),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image2',
            field=models.ImageField(blank=True, upload_to=coplate.models.cafe_image_upload_to),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image3',
            field=models.ImageField(blank=True, upload_to=coplate.models.cafe_image_upload_to),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image4',
            field=models.ImageField(blank=True, upload_to=coplate.models.cafe_image_upload_to),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image5',
            field=models.ImageField(blank=True, upload_to=coplate.models.cafe_image_upload_to),
        ),
    ]
